@startuml "Overview"

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/AWSSimplified.puml
!include AWSPuml/General/Users.puml
!include AWSPuml/General/Client.puml
!include AWSPuml/Groups/AWSCloud.puml
!include AWSPuml/Storage/SimpleStorageService.puml
!include AWSPuml/ApplicationIntegration/APIGateway.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Database/DynamoDB.puml
!include AWSPuml/Analytics/KinesisDataStreams.puml

title "Overview"
left to right direction

skinparam rectangle {
    BackgroundColor AWS_BG_COLOR
    BorderColor transparent
}

Users(users, "Users", "...")
Client(browser, "Browser", "...")
AWSCloudGroup(cloud){
    SimpleStorageService(videoUi, "Video UI", "...")
    APIGateway(apiGateway, "REST API", "...")
    Lambda(authorizer, "Authorizer", "...")
    Lambda(apiTest, "API Test", "...")
    Lambda(recordViewings, "Record Viewings", "...")
    DynamoDB(messagesTable, "Messages Table", "...")
    KinesisDataStreams(dataStream, "Data Stream", "...")
    Lambda(aggregateVideosViewed, "Aggregate Total Videos Viewed", "...")
    DynamoDB(pagesTable, "Pages Table", "...")
    Lambda(getPage, "Get page", "...")

    users --> browser
    browser --> videoUi
    browser --> apiGateway
    apiGateway --> authorizer
    apiGateway --> apiTest
    apiGateway --> recordViewings
    apiGateway --> getPage
    getPage -----> pagesTable
    recordViewings --> messagesTable
    messagesTable --> dataStream
    dataStream --> aggregateVideosViewed
    aggregateVideosViewed --> pagesTable
}

@enduml
