@startuml Overview

!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v14.0/dist
!include AWSPuml/AWSCommon.puml
!include AWSPuml/General/Users.puml
!include AWSPuml/ApplicationIntegration/APIGateway.puml
!include AWSPuml/Analytics/KinesisDataStreams.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Database/DynamoDB.puml

left to right direction

title "Overview"

Users(users, "Users", "...")
APIGateway(apiGateway, "API", "...")
Lambda(appRecordViewings, "record-viewings", "record video viewings")
DynamoDB(messageStore, "Message Store", "message table")
KinesisDataStreams(eventStream, "Stream", "...")
Lambda(app1, "Aggregator", "...")
Lambda(app2, "Component", "...")
Lambda(app3, "...", "...")
Lambda(appApiTest, "api-test", "hello from lambda")
Lambda(authorizer, "authorizer", "api key validation")

users --> apiGateway
apiGateway --> authorizer
apiGateway --> appApiTest
apiGateway --> appRecordViewings
appRecordViewings --> messageStore
messageStore --> eventStream
eventStream --> app1
eventStream --> app2
eventStream --> app3
@enduml
