name: "Test and diff stack"

on:
  push:
    branches:
      - 'feature/**'

jobs:
  terraform:
    name: "Terraform CDK Diff"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install application dependencies
        run: npm ci
        working-directory: ./application

      - name: Run application tests
        run: npm test
        working-directory: ./application

      - name: Build applications
        run: npm run build
        working-directory: ./application

      - name: Install ui dependencies
        run: npm ci
        working-directory: ./ui

      - name: Lint ui
        run: npm run lint
        working-directory: ./ui

      - name: Build ui
        run: npm run build
        working-directory: ./ui

      - name: Install infrastructure dependencies
        run: npm ci
        working-directory: ./infrastructure

      - name: Generate infrastructure module and provider bindings
        run: npx cdktf-cli get
        working-directory: ./infrastructure

      - name: Generate infrastructure diff
        run: npx cdktf diff
        working-directory: ./infrastructure



