name: "Apply Stack after PR is Merged"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform CDK Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install application dependencies
        run: npm ci
        working-directory: ./application

      - name: Run application tests
        run: npm test
        working-directory: ./application

      - name: Build application
        run: npm run build
        working-directory: ./application

      - name: Install infrastructure dependencies
        run: npm ci
        working-directory: ./infrastructure

      - name: Generate infrastructure module and provider bindings
        run: npx cdktf-cli get
        working-directory: ./infrastructure

      - name: Deploy infrastructure
        run: npx cdktf deploy --auto-approve
        working-directory: ./infrastructure

      - name: Build ui
        run: npm run build
        working-directory: ./ui

      - name: Deploy ui
        run: npm run deploy
        working-directory: ./ui
